### ISSUE TITLE
Accessible date picker for CDS

### ISSUE THREAD

**Issue by abby-lammers** [Chicago/design-cds-bootstrap#15]
For entering or selecting a date, USWDS provides a three-box system: 

![image](https://user-images.githubusercontent.com/26829620/64814923-1362c300-d56a-11e9-894e-85d65cd4f009.png)

For most date selection cases, the USWDS date picker component is sufficient. This is the most accessible option for entering a date. Calendar date pickers tend to be difficult, sometimes impossible, for keyboard-only users to navigate.

A calendar date picker may be needed in situations where restricting dates by availability is important. If a calendar date picker is needed, be sure to follow accessibility guidelines. [Axesslab](https://axesslab.com/accessible-datepickers/)
 provides multiple good resources for learning about date picker accessibility.

**Comment by jdkunesh** [comment]
@alaeder16 @mario-duran @chrisjcalderon how does this look to folks? Seems to have a good WCAG2 AA pedigree and works with Bootstrap 4:

https://github.com/eureka2/ab-datepicker

**Comment by alaeder16** [comment]
You mean like no icon at all?
![image](https://user-images.githubusercontent.com/57451859/69365584-47d5b800-0c5a-11ea-877e-1b839caceb5d.png)

**Comment by jdkunesh** [comment]
No, let's go with the direction we chose yesterday. We can use this kind of visualization (and eventually component):

http://eureka2.github.io/ab-datepicker/

as an accessible Bootstrap component (https://github.com/eureka2/ab-datepicker) instead of the USWDS [mm] [dd] [yyyy] format we have today.

<img width="368" alt="Screen Shot 2019-11-20 at 3 01 46 PM" src="https://user-images.githubusercontent.com/157725/69365794-aac74f00-0c5a-11ea-9139-f61e9dd75d6e.png">

**Comment by alaeder16** [comment]
ok, great. I added it to Figma in components

**Comment by jdkunesh** [comment]
Will integrate this item as a submodule.

**Comment by mario-duran** [comment]
Added a quick example on the main kitchen sink home page and added a full set of examples in the Components Page
